AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'city_guide_app

  Sample SAM Template for city_guide_app

  '
Globals:
  Function:
    Timeout: 3
Resources:
  CityGuideFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://lab-alexa-city-guide-deployment/5937d96d0707b7547f504d8fa2566ccc
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: arn:aws:iam::075778139020:role/money2020_poc
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill
          Properties:
            SkillId: amzn1.ask.skill.9524a157-da01-4d73-abe8-60f2a70e30c6
Outputs:
  CityGuideFunction:
    Description: Lambda function for city guide
    Value:
      Fn::GetAtt:
      - CityGuideFunction
      - Arn
