AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  city_guide_app

  Sample SAM Template for city_guide_app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  CityGuideFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: city_guide/
      Handler: app.lambda_handler
      Runtime: python3.7
      Role: arn:aws:iam::075778139020:role/money2020_poc
      Events:
        AlexaSkillEvent:
          Type: AlexaSkill # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            SkillId: amzn1.ask.skill.9524a157-da01-4d73-abe8-60f2a70e30c6

Outputs:
  CityGuideFunction:
    Description: Lambda function for city guide
    Value: !GetAtt CityGuideFunction.Arn